ITS_System/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ITS_System.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ITS_System/Areas/Customer/Controllers/BookingController.cs
using ITS_System.Data;
using ITS_System.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlexAppealFitness.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class BookingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public BookingController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string searchString)
        {
            var classSchedules = from c in _context.Schedule
                                 select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                classSchedules = classSchedules.Where(s => s.Instructor.Email.Contains(searchString) || s.DateTime.ToString().Contains(searchString));
            }

            return View(await classSchedules.Include("Instructor").Include("Room").OrderBy(s => s.DateTime).ToListAsync());
        }

        public async Task<IActionResult> Book(int Id)
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);

            if (currentUser == null)
            {
                return NotFound();
            }

            Booking book = new Booking();

            book.ClassId = Id;
            book.AttendeeId = currentUser.Id;
            book.TimeStamp = DateTime.Now;
            book.Attendee = currentUser;

            var currentClass = await _context.Schedule.FindAsync(Id);

            if (currentClass == null)
            {
                return NotFound();
            }

            bool doubleBook = currentClass.Attendees.Any(a => a.AttendeeId == currentUser.Id);

            if (doubleBook)
            {
                return RedirectToAction("Index", "Bookings");
            }

            book.Class = currentClass;

            currentClass.Attendees.Add(book);
            currentClass.AvailableSpaces = currentClass.MaxNumbersOfBooking - currentClass.Attendees.Count();
            _context.Schedule.Update(currentClass);

            await _context.SaveChangesAsync();



            return RedirectToAction(nameof(Index));
        }


    }
}

ITS_System/Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITS_System.Data;
using ITS_System.Models;
using FlexAppealFitness.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Identity;

namespace FlexAppealFitness.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize(Roles = "Customer, Admin")]
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ViewClasses()
        {
            var applicationDbContext = _context.Schedule.Include(c => c.Room).Include(c => c.Instructor);
            return View(await applicationDbContext.ToListAsync());
        }
    }
}

ITS_System/Controllers/HomeController.cs
using ITS_System.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ITS_System.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ITS_System/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Customer Dashboard";
}

<div class="text-center">
    <h1 class="display-4">Customer Dashboard</h1>  
</div>

<div class = "container">
    <div class="container text-center">
        <div class="row">
            <div class="col-4 mt-3">
                <div class="card" style="width: 25rem; height: 25rem">
                  <div class="card-body d-flex flex-column justify-content-between">
                    <h5 class="card-title"></h5>
                    <p class="card-text">Click to Vew Classes</p>
                    <div class = "card-footer">
                        <a class="btn btn-primary mx-auto" asp-area="Customer" asp-controller="Home" asp-action="ViewClasses">View Classes</a>
                    </div>
                  </div>
                </div>  
            </div>
            <div class="col-4 mt-3">
                <div class="card" style="width: 25rem; height: 25rem">
                  <div class="card-body d-flex flex-column justify-content-between">
                    <h5 class="card-title"></h5>
                    <p class="card-text">Click to view bookings</p>
                    <div class = "card-footer">
                        <a class="btn btn-primary mx-auto" asp-area="Customer" asp-controller="Booking" asp-action="Index">View Bookings</a>
                    </div>
                  </div>    
                </div>  
            </div>
            <div class="col-4 mt-3">
                <div class="card" style="width: 25rem; height: 25rem">
                  <div class="card-body d-flex flex-column justify-content-between">
                    <h5 class="card-title"></h5>
                    <p class="card-text">Click to view bookings</p>
                    <div class = "card-footer">
                        <a class="btn btn-primary mx-auto" asp-area="Customer" asp-controller="Bookings" asp-action="Index">Manage Bookings</a>
                    </div>
                  </div>    
                </div>  
            </div>
        </div>
    </div>
</div>

ITS_System/Areas/Customer/Views/Home/ViewClasses.cshtml
@model IEnumerable<ITS_System.Models.ClassSchedule>

@{
    ViewData["Title"] = "Class Schedule";
}



<h1>Class Schedule</h1>

<div class = "d-flex flex-wrap justify-content-between" style="margin-left:2vh;margin-right:2vh;">
    @foreach (var item in Model)
    {
        <div class = "col-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
                    <h6 class="card-subtitle mb-2 text-muted">@Html.DisplayFor(modelItem => item.DateTime)</h6>
                    <h6 class="card-subtitle mb-2 text-muted">@Html.DisplayFor(modelItem => item.MaxNumbersOfBooking)</h6>
                    <h6 class="card-subtitle mb-2 text-muted">@Html.DisplayFor(modelItem => item.Room.Description)</h6>
                    <h6 class="card-subtitle mb-2 text-muted">@Html.DisplayFor(modelItem => item.Status)</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Another link</a>
                </div>
            </div>
        </div>
    }
</div>

<div style = "margin-left: 10%;">
    <a asp-action="Index" asp-controller = "Home">Back to List</a> 
</div>