ITS_System/Areas/Admin/Controllers/RolesManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ITS_System.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RolesManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesManagerController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> DeleteRole(string Id)
        {
            if (Id != null)
            {
                var role = await _roleManager.FindByIdAsync(Id);

                if (role != null)
                {
                    await _roleManager.DeleteAsync(role);
                    ViewBag.Message = $"{ role.Name } deleted.";
                }

            }
            return RedirectToAction(nameof(Index), ViewBag);
        }
    }
}

ITS_System/Areas/Admin/Views/RolesManager/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>


@{
    ViewData["Title"] = "Roles Manager Page";
}

    <div class="text-center">
        <h1 class="display-4">Roles Manager</h1>  

        @if (ViewBag.Message != null)
        {
            <div class="alert alert-danger mx-2">@ViewBag.Message</div>
        }

    <form method="post" asp-action="AddRole" asp-controller="RolesManager">
        <div class="input-group">
            <input name="roleName" class="form-control w-25" />
            <span class="input-group-btn">
                <button type="submit" class="btn-info btn">Add New Role</button>
            </span>
        </div>
    </form>

    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Role Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var role in Model)
            {
                <tr>
                    <td>@role.Id</td>
                    <td>@role.Name</td>
                    <td>
                        <a class="btn btn-danger" asp-action="DeleteRole" asp-route-id="@role.Id">Delete</a>
                    </td>
                </tr>
            }


        </tbody>
    </table>


</div>

<div>
    <a asp-action="Index" asp-controller = "Home">Back to List</a> 
</div>